language: go
dist: bionic
before_install:
  - sudo apt update
  - sudo apt install softhsm
  - sudo mkdir -p /var/lib/softhsm/tokens
  - softhsm2-util --init-token --slot 0 --label hsm --pin 1234 --so-pin 1234

go:
  - 1.x
  - 1.13.x
  - master
