language: go

services:
  - docker

before_install:
  - docker build -t niclabs/dns-tools .
  - docker run niclabs/dns-tools sh -c 'go test ./...'

script:
  - go test ./...

go:
  - 1.x
  - 1.13.x
  - master
